### ISSUE TITLE
Keep getting the Nullreference when adding the Discord Manager into the scene

### ISSUE THREAD

**Issue by Nielsiee** [eslam980/Ultimate-Discord-SDK#2]
NullReferenceException: Object reference not set to an instance of an object
UDiscord.DiscordManager.Update () (at Assets/Plugins/DiscordGameSDK/DiscordManager.cs:40)

**Comment by eslam980** [comment]
I am working on An Big Update for the SDK will release soon , sorry for your trouble but you can download the "Ultimate Discord SDK.unitypackage" , it's the most LTS version here.

**Comment by Nielsiee** [comment]
Alrighty, though unity keeps giving the error the package has some errors

**Comment by eslam980** [comment]
if you have any problem with it you can contact me or add me in discord " eslam980#9639 " , I'm working on adding so much Features to make it easier for everyone to use it.

**Comment by Nielsiee** [comment]
alrighty, will do
